package com.safephone.ui

/** Semantics test tags for UI / E2E tests. */
object SafePhoneTestTags {
    const val ONBOARDING_FINISH = "onboarding_finish"
    const val HOME_BREAKS_BALANCE = "home_breaks_balance"
    const val HOME_START_BREAK = "home_start_break"
    const val HOME_NAV_BLOCKED = "home_nav_blocked"
    const val HOME_NAV_DOMAINS = "home_nav_domains"
    const val HOME_NAV_BUDGETS = "home_nav_budgets"
    const val HOME_NAV_BREAKS = "home_nav_breaks"
    const val HOME_NAV_EXPORT = "home_nav_export"
    const val HOME_NAV_BLOCK_STATS = "home_nav_block_stats"
    const val BLOCK_STATS_EMPTY = "block_stats_empty"
    const val BLOCKED_SEARCH_FIELD = "blocked_search_field"
    /** LazyColumn item: manual package entry card (below installed-app list). */
    const val BLOCKED_MANUAL_SECTION = "blocked_manual_section"
    const val BLOCKED_PACKAGE_FIELD = "blocked_package_field"
    const val BLOCKED_ADD = "blocked_add"
    const val BLOCKED_REMOVE_PREFIX = "blocked_remove_"
    const val DOMAIN_PATTERN_FIELD = "domain_pattern_field"
    const val DOMAIN_ADD = "domain_add"
    const val DOMAIN_REMOVE_PREFIX = "domain_remove_"
    const val BUDGET_SEARCH_FIELD = "budget_search_field"
    const val BUDGET_PACKAGE_FIELD = "budget_package_field"
    const val BUDGET_MINUTES_FIELD = "budget_minutes_field"
    const val BUDGET_SAVE = "budget_save"
    const val BUDGET_REMOVE_PREFIX = "budget_remove_"
    const val BREAKS_MAX_FIELD = "breaks_max_field"
    const val BREAKS_DURATION_FIELD = "breaks_duration_field"
    const val BREAKS_GAP_FIELD = "breaks_gap_field"
    const val BREAKS_SAVE = "breaks_save"
    const val EXPORT_GENERATE = "export_generate"
    const val EXPORT_SHARE = "export_share"
    const val EXPORT_JSON_TEXT = "export_json_text"
}
