#!/usr/bin/env node
// Writes src/generated/config.js with the credentials baked in.
//
// Reads from process.env so this script can be driven by either:
//   - Local devs: `SAFEPHONE_CLOUD_SYNC_DEFAULT_GITHUB_TOKEN=... SAFEPHONE_CLOUD_SYNC_DEFAULT_GIST_ID=... npm run build:config`
//   - CI: the chrome-extension-zip workflow exports the same two env vars from repo secrets.
//
// Mirrors the Android pattern in .github/workflows/android-branch-apk.yml,
// where the matching BuildConfig fields are baked into the APK at build time.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outDir = path.resolve(__dirname, "..", "src", "generated");
const outFile = path.join(outDir, "config.js");

const token = process.env.SAFEPHONE_CLOUD_SYNC_DEFAULT_GITHUB_TOKEN ?? "";
const gistId = process.env.SAFEPHONE_CLOUD_SYNC_DEFAULT_GIST_ID ?? "";

const body = `// AUTO-GENERATED by scripts/build-config.js. Do not edit by hand and do not commit.
export const CLOUD_SYNC_DEFAULT_GITHUB_TOKEN = ${JSON.stringify(token)};
export const CLOUD_SYNC_DEFAULT_GIST_ID = ${JSON.stringify(gistId)};
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, body, "utf8");

const tokenStatus = token ? `set (len=${token.length})` : "empty";
const gistStatus = gistId ? `set (len=${gistId.length})` : "empty";
console.log(`Wrote ${path.relative(process.cwd(), outFile)} — token: ${tokenStatus}, gistId: ${gistStatus}`);
